### ISSUE TITLE
"dumb binary" on PYPI leads to installation problem

### ISSUE THREAD

**Issue by tychoish** [tkruse/cpplint#1]
I'm getting errors trying to install cpplint, using pip. Looks related to this problem: https://github.com/aelse/python-crowd/issues/1

I think it's safe to remove the dumb binary package, given that cpplint is pure-python.

**Comment by tychoish** [comment]
See #2 for a documentation fix to address this issue moving forward.

**Comment by tkruse** [comment]
ok, merged #2 and manually removed bdist from pypi

**Comment by tkruse** [comment]
Can you try again installing from pypi and confirm that it works? Close issue if so.

**Comment by tychoish** [comment]
bingo! thanks
