### ISSUE TITLE
cpp linting for coala

### ISSUE THREAD

**Issue by sils1297** [tkruse/cpplint#3]
Hey! I'm the main developer of a little project called coala (see https://github.com/coala-analyzer/coala/ ). It makes it very easy to create "code checking routines" and provide you with the whole user interaction (from JSON output via interactive CLI UI to an actual GUI and we're working on things like direct GitHub integration [as a service] and stuff like that) and collection routines for free.

We would love to have cpplint's functionality in coala, there are two ways to do that:

# Porting your Routines to coala

This is the best way but a bit more work of course :) It comes with the following advantages:

 * We'd maintain the stuff, ideally together.
 * More shared code, thus less code to maintain overall, we do the user interaction completely for you. Focus on the logic, let the annoying stuff to coala.
 * You get coala's flexibility. Results can have patches attached so coala can auto-fix issues, issues can relate to multiple results.

Since your code is already in python, porting it shouldn't be that hard or take much work.

# Wrapping around

I totally understand if you're not interested in a port. In that case we'd probably do a wrapper on our own.

**Comment by tkruse** [comment]
I am not the original author, nor maintaining. Maybe ask at https://github.com/ondrasej/cpplint

**Comment by sils1297** [comment]
Thanks for the quick reply!
